# Generated by Django 4.1.2 on 2022-11-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_client_image_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, upload_to='myapp/static/images'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
